export enum Permission {
  CONTROL_PLANE_READ = 'CONTROL_PLANE_READ',
  PROJECT_MANAGE = 'PROJECT_MANAGE',
  FLAG_MANAGE = 'FLAG_MANAGE',
  FLAG_LIFECYCLE_MANAGE = 'FLAG_LIFECYCLE_MANAGE',
  RULE_MANAGE = 'RULE_MANAGE',
  GROUP_MANAGE = 'GROUP_MANAGE',
  GROUP_ASSIGN = 'GROUP_ASSIGN',
  GROUP_KILL_SWITCH = 'GROUP_KILL_SWITCH',
  SAMPLE_USER_MANAGE = 'SAMPLE_USER_MANAGE',
}
